boletas/urls.py
from django.conf.urls import url 
from . import views 

urlpatterns = [
	url(r'^grupos$', views.GruposList.as_view(), name="grupos"),
	url(r'^grupo/crear$', views.GruposCreate.as_view(), name="crear_grupo")
]

cuentas/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth.views import logout, logout_then_login, login


from .api import urls as UrlsAPICuentas

urlpatterns = [
	url(r'^registro/$', views.Registro.as_view(), name="registro"),
	url(r'^registro/alumno/$', views.RegistroAlumno.as_view(), name="registro_alumno"),
	url(r'^api/', include(UrlsAPICuentas, namespace="api")),
	url(r'^padres/$', views.PadresListView.as_view(), name="padres"),
	url(r'^profesores/$', views.ProfesListView.as_view(), name="profesores"),
	url(r'^profile/$', views.Dashboard.as_view(), name="perfil"),
	url(r'^login/$', login, name="login"),
  url(r'^logout/$', logout, name="logout"),
  url(r'^logout-then-login/$', logout_then_login, name="logout_then_login"),
]

grades/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from main import urls as UrlsMain
from cuentas import urls as UrlsCuentas
from boletas import urls as UrlsBoletas

from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(UrlsMain, namespace='main')),
    url(r'^accounts/', include(UrlsCuentas, namespace='cuentas')),
    url(r'^boletas/', include(UrlsBoletas, namespace='boletas')),
    url(
        regex=r'^media/(?P<path>.*)/$',
        view=serve,
        kwargs={"document_root":settings.MEDIA_ROOT}
        )
]

main/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^$', views.Home.as_view(), name='home'),
]

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Grades | Home</title>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
	<link rel="stylesheet" href="{%static 'css/main.css'%}">
  <style>
    .no-margin{
      margin: 0;
    }
    img.cover{
      position: absolute;
      min-width: 100%;
      max-width: 100% !important;
      height: 50%;
    }
    nav{
      box-shadow: none !important;
    }
  </style>
</head>
<body>
	
  <div class="white row no-margin">
   
      {%block cover%}
      {%endblock cover%}
    
  </div>

  <nav>
    <div class="nav-wrapper blue accent-2 z-depth-1">
      <a href="/" class="brand-logo">Easy-Grades</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="#!">Alumnos</a></li>
        <li><a href="{%url 'cuentas:profesores' %}">Profesores</a></li>
        <li><a href="{%url 'boletas:grupos'%}">Grupos</a></li>
        {%if request.user.is_authenticated%}
          <li><a href="{%url 'cuentas:logout'%}">Cerrar Sesion</a></li>
          <li><a href="{%url 'cuentas:perfil'%}">Perfil</a></li>
        {%endif%}
      </ul>
      <ul class="side-nav" id="mobile-demo" style="z-index:1000;">
        <li><a href="#!">Alumnos</a></li>
        <li><a href="{%url 'cuentas:profesores' %}">Profesores</a></li>
        <li><a href="{%url 'boletas:grupos'%}">Grupos</a></li>
        {%if request.user.is_authenticated%}
          <li><a href="{%url 'cuentas:logout'%}">Cerrar Sesion</a></li>
          <li><a href="{%url 'cuentas:perfil'%}">Perfil</a></li>
        {%endif%}
      </ul>
    </div>
  </nav>
  
  

	<section class="section row">

		<div class="col s12 m8 row">
      <div class="card col s12 white">
        <div class="card-content">
          <span class="card-title"><h1>{%block titulo%}{%endblock titulo%}</h1></span>
          
          <div class="row flow-text padding-top">
          	{%block content%}
          	{%endblock content%}
          </div>

        </div>
        
      </div>
    </div>

  	<div class="col s12 m4 row">
      <div class="card col s12 blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Opciones - {%if request.user.profesor%}Profesor{%elif request.user.alumno%}Alumno{%elif request.user.padre%}Padre{%endif%} </span>
          
          <ul>
        		{%if request.user.is_authenticated%}
              {%block opciones%}
                {%if request.user.profesor%}
                  <li><a href="{%url 'boletas:crear_grupo'%}">Crear un Grupo</a></li>
                  <li><a href="{%url 'boletas:grupos'%}">Mis Grupos</a></li>
                {%endif%}
	          	{%endblock opciones%}
						{%else%}
							<p>Autenticate para ver opciones.</p>
		        {%endif%}
          </ul>

        </div>
        <div class="card-action">
        	{%if request.user.is_authenticated and request.user.padre%}
	          <a href="#">Revisa boleta de tu hijo</a>
	          <a href="#">Contancta a su profesor</a>
          {%elif request.user.is_authenticated and request.user.profesor%}
            <a href="#!">Subir Calificaciones</a>
          {%elif request.user.is_authenticated and request.user.alumno%}
            <a href="#!">Ver Calificaciones</a>
					{%else%}
						<a href="{%url 'cuentas:login'%}">Inicia Sesión</a>
	          <a href="{%url 'cuentas:registro'%}">Registrate</a>
	        {%endif%}
        </div>
      </div>

      <div class="card col s12 blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Extras - {%if request.user.profesor%}Profesor{%elif request.user.alumno%}Alumno{%elif request.user.padre%}Padre{%endif%} </span>
          
          {%block extras%}

          {%endblock extras%}


        </div>
        <div class="card-action">
          {%if request.user.is_authenticated and request.user.padre%}
            <a href="#">Revisa boleta de tu hijo</a>
            <a href="#">Contancta a su profesor</a>
          {%elif request.user.is_authenticated and request.user.profesor%}
            <a href="#!">Subir Calificaciones</a>
          {%elif request.user.is_authenticated and request.user.alumno%}
            <a href="#!">Ver Calificaciones</a>
          {%else%}
            <a href="{%url 'cuentas:login'%}">Inicia Sesión</a>
            <a href="{%url 'cuentas:registro'%}">Registrate</a>
          {%endif%}
        </div>
      </div>
    </div>

	</section>
	
	
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
  <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
  <script>
  	$(".button-collapse").sideNav();
    

  	{%block scripts%}

  	{%endblock scripts%}
  </script>
</body>
</html>